'use strict';
const $=id=>document.getElementById(id),token=document.body.dataset.token;
const endpoint=(path,params={})=>{const u=new URL(path,location.href);u.searchParams.set('access_token',token);for(const [k,v] of Object.entries(params))u.searchParams.set(k,v);return u.href;};
const normalized=value=>value.replace(/\s/g,'').toUpperCase();
const validCode=value=>/^[1-9]\d{8}$/.test(value)||/^[A-F0-9]{24}$/.test(value);
const formatted=value=>/^\d{9}$/.test(value)?value.replace(/(\d{3})(?=\d)/g,'$1 '):value;
let local=null,records=[],signature='',revealPIN=true,checkSequence=0,checkTimer,submitting=false;
let devicePage=0;
let pendingPIN='',pinRotating=false,pinRequest=0;
let meetingSubmitting=false,meetingUntil=0;
const statuses=new Map();
function notice(message){$('notice').textContent=message;$('notice').hidden=!message;}
async function request(path,data,params){const r=await fetch(endpoint(path,params),{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data),cache:'no-store',signal:AbortSignal.timeout(path.includes('activate')?20000:6000)});if(!r.ok)throw Error((await r.text()).slice(0,300));return r.json();}
function tab(name){for(const pane of document.querySelectorAll('.pane'))pane.hidden=pane.id!=='pane-'+name;for(const button of document.querySelectorAll('nav [data-tab]'))button.classList.toggle('selected',button.dataset.tab===name);$('pageTitle').textContent=({remote:'远程控制',meeting:'会议',devices:'设备列表',files:'文件传输',settings:'设置'})[name];if(name==='devices')loadDevices();}
for(const button of document.querySelectorAll('[data-tab]'))button.onclick=()=>tab(button.dataset.tab);
$('homeBrand').onclick=event=>{event.preventDefault();tab('remote');};
fetch(endpoint('/api/ui/watch')).catch(()=>{});
function updateLocal(s){if(local&&(s.pinRevision||0)<(local.pinRevision||0))s={...s,pin:local.pin,pinSynced:local.pinSynced,pinRevision:local.pinRevision};local=s;$('sidebarName').textContent=s.name;$('localName').textContent=s.name;$('localCode').textContent=s.code?formatted(s.code):'正在分配';$('localPIN').textContent=revealPIN?s.pin:'••••••';$('receiving').checked=s.receiving;$('filePermission').checked=s.files;$('receiveDirectory').textContent=s.fileDirectory;$('licenseLabel').textContent='设备授权：'+s.activeUntil;$('serverDot').classList.toggle('online',s.online);$('serverState').textContent=s.online?'服务器已连接':'连接服务器中';$('localState').textContent=!s.receiving?'已暂停接入':s.connected?'连接中':!s.online?'正在连接':s.active?'在线待连接':'等待激活';$('localState').className='badge '+(!s.receiving?'neutral':s.connected||s.online&&s.active?'good':'warning');$('copyCode').disabled=!s.code;$('copyBoth').disabled=!s.code;if(s.code)statuses.set(s.code,{online:s.online,connected:s.connected,active:s.active,ready:s.active&&s.online&&s.receiving&&!s.connected});updateMeeting(s);updateBadges();}
async function refreshLocal(){const generation=pinRequest;try{const value=await request('/api/local/status');if(generation===pinRequest&&!pinRotating)updateLocal(value);if(pendingPIN&&value.pin===pendingPIN&&value.pinSynced){pendingPIN='';notice('PIN 已更换并同步后台，旧 PIN 已失效');}}catch(_){}setTimeout(refreshLocal,2000);}
refreshLocal();
$('rotatePIN').onclick=async()=>{if(pinRotating)return;pinRotating=true;pinRequest++;const button=$('rotatePIN');button.disabled=true;try{await request('/api/local/pin/rotate',{});const value=await request('/api/local/status');pendingPIN=value.pin;updateLocal(value);notice(value.pinSynced?'PIN 已更换并同步后台，旧 PIN 已失效':'PIN 已更换，旧 PIN 已失效；正在同步后台…');if(value.pinSynced)pendingPIN='';}catch(error){notice('更换结果未确认，请核对当前 PIN：'+error.message);}finally{pinRotating=false;button.disabled=false;pinRequest++;}};
async function copy(value,label){if(!value)return;try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(value);else{const area=document.createElement('textarea');area.value=value;area.style.cssText='position:fixed;opacity:0';document.body.append(area);area.select();const copied=document.execCommand('copy');area.remove();if(!copied)throw Error('copy');}notice(label+'已复制');}catch(_){notice('复制失败，请手动选择复制');}}
$('copyCode').onclick=()=>copy(local?.code,'设备码');$('copyPIN').onclick=()=>copy(local?.pin,'PIN');$('copyBoth').onclick=()=>copy(local?.code?'设备码：'+local.code+'\nPIN：'+local.pin:'','设备码和 PIN');$('togglePIN').onclick=()=>{revealPIN=!revealPIN;if(local)updateLocal(local);};
function formatMeeting(value){return value.replace(/\D/g,'').slice(0,9).replace(/(\d{3})(?=\d)/g,'$1 ');}
function updateMeeting(s){const active=!!s.meeting&&/^[1-9]\d{8}$/.test(s.meetingCode||'')&&Date.parse(s.meetingUntil)>Date.now();$('meetingIdle').hidden=active;$('meetingActive').hidden=!active;$('meetingDot').hidden=!active;meetingUntil=active?Date.parse(s.meetingUntil):0;if(active){$('meetingCode').textContent=formatMeeting(s.meetingCode);$('copyMeeting').dataset.code=s.meetingCode;$('meetingActive').querySelector('.meeting-meta span:first-child').lastChild.textContent=s.connected?'参与者已连接':'等待参与者';}else{$('meetingCode').textContent='—';$('copyMeeting').dataset.code='';}}
function refreshMeetingCountdown(){if(!meetingUntil){$('meetingCountdown').textContent='—';return;}const seconds=Math.max(0,Math.ceil((meetingUntil-Date.now())/1000)),hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60);$('meetingCountdown').textContent=seconds<=0?'已到期':'剩余 '+(hours?hours+'小时 ':'')+(minutes||!hours?minutes+'分':'');}
setInterval(refreshMeetingCountdown,1000);refreshMeetingCountdown();
$('startMeeting').onclick=async()=>{const button=$('startMeeting');button.disabled=true;try{await request('/api/local/meeting/start',{});const value=await request('/api/local/status');updateLocal(value);tab('meeting');notice('会议已创建，会议号两小时内有效');}catch(error){notice(error.message);}finally{button.disabled=false;}};
$('copyMeeting').onclick=()=>{const code=$('copyMeeting').dataset.code;if(code)copy('YuDesk 会议号：'+formatMeeting(code)+'\n输入会议号即可加入 · 仅观看','会议号');};
$('endMeeting').onclick=async()=>{if(!await window.yudeskConfirm('结束本次会议？会议号会立即失效，已加入的参与者也会断开。'))return;const button=$('endMeeting');button.disabled=true;try{await request('/api/local/meeting/end',{});updateLocal(await request('/api/local/status'));notice('会议已结束，原会议号已失效');}catch(error){notice(error.message);}finally{button.disabled=false;}};
function meetingParts(){const value=$('meetingInvite').value.replace(/\D/g,'');return /^[1-9]\d{8}$/.test(value)?{code:value}:null;}
let meetingCheckSequence=0,meetingCheckTimer;
function checkMeeting(delay=350){const seq=++meetingCheckSequence;clearTimeout(meetingCheckTimer);const parts=meetingParts();$('meetingStatus').className='presence';$('meetingStatus').textContent=parts?'查询会议状态…':'输入正确会议号即可直接加入';if(!parts)return;meetingCheckTimer=setTimeout(async()=>{try{const room=await request('/api/local/meeting/resolve',undefined,{code:parts.code}),rows=await queryStatuses([room.id]);if(seq!==meetingCheckSequence)return;const s=rows.find(row=>row.id===room.id);$('meetingStatus').textContent=!s?.online?'主持电脑离线':s.connected?'会议已有参与者':!s.active?'主持电脑尚未激活':'会议进行中 · 可以直接加入';$('meetingStatus').className='presence '+(s?.online&&!s.connected&&s.active?'online':'offline');}catch(_){if(seq===meetingCheckSequence){$('meetingStatus').textContent='会议不存在、已结束或已过期';$('meetingStatus').className='presence offline';}}},delay);}
$('meetingInvite').oninput=()=>{$('meetingInvite').value=formatMeeting($('meetingInvite').value);checkMeeting();};
$('meetingInvite').addEventListener('paste',event=>{const text=event.clipboardData?.getData('text')||'',digits=text.replace(/\D/g,'');if(digits.length===9){event.preventDefault();$('meetingInvite').value=formatMeeting(digits);checkMeeting(0);}});
$('meetingJoinForm').onsubmit=async event=>{event.preventDefault();if(meetingSubmitting)return;const parts=meetingParts();if(!parts){notice('请输入 9 位会议号');return;}meetingSubmitting=true;$('joinMeeting').disabled=true;try{const room=await request('/api/local/meeting/resolve',undefined,{code:parts.code});if(local&&room.id===local.id)throw Error('不能加入自己发起的会议');const rows=await queryStatuses([room.id]),s=rows.find(row=>row.id===room.id);if(!s?.online)throw Error('主持电脑离线，请先联系主持人打开 YuDesk');if(s.connected)throw Error('会议已有参与者，请稍后重试');if(!s.active)throw Error('主持电脑尚未激活');$('meetingDeviceID').value=room.id;$('meetingPIN').value=parts.code;HTMLFormElement.prototype.submit.call(event.target);}catch(error){notice(error.message);meetingSubmitting=false;$('joinMeeting').disabled=false;}};
for(const [id,path] of [['receiving','receiving'],['filePermission','files']])$(id).onchange=async()=>{const control=$(id);control.disabled=true;try{await request('/api/local/'+path,{enabled:control.checked});updateLocal(await request('/api/local/status'));}catch(error){notice(error.message);control.checked=!control.checked;}finally{control.disabled=false;}};
$('activateForm').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;try{await request('/api/local/activate',{key:$('activationKey').value});$('activationKey').value='';$('activation').open=false;notice('授权已提交，请稍候同步状态');updateLocal(await request('/api/local/status'));}catch(error){notice(error.message);}finally{button.disabled=false;}};
$('hideApp').onclick=async()=>{try{await request('/api/local/hide',{});}catch(error){notice(error.message);}};
function state(status){if(!status)return ['检测中','neutral'];if(!status.online)return ['离线','neutral'];if(status.connected)return ['连接中','good'];if(!status.active)return ['未激活','warning'];if(status.ready===false)return ['准备中','warning'];return ['在线','good'];}
function updateBadges(){for(const el of document.querySelectorAll('[data-presence-id]')){const [text,color]=state(statuses.get(el.dataset.presenceId));el.textContent=text;el.className='badge '+color;}for(const el of document.querySelectorAll('[data-dot-id]'))el.classList.toggle('online',!!statuses.get(el.dataset.dotId)?.online);}
function selectDevice(id){tab('remote');$('targetCode').value=formatted(id);$('targetPIN').value='';$('targetPIN').focus();scheduleCheck();}
function makeIcon(id){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),use=document.createElementNS(svg.namespaceURI,'use');use.setAttribute('href','#'+id);svg.append(use);return svg;}
function renderDevices(force=false){const data=[...(local?[{deviceID:local.code||local.id,name:local.name,local:true}]:[]),...records].map(r=>({...r,displayCode:statuses.get(r.deviceID)?.deviceCode||r.deviceID}));const next=JSON.stringify(data);if(!force&&next===signature){updateBadges();return;}signature=next;const fragment=document.createDocumentFragment();for(const record of data){const row=document.createElement('div');row.className='device-row';row.dataset.search=(record.name+' '+record.deviceID+' '+record.displayCode).toLowerCase();const nameCell=document.createElement('div'),label=document.createElement('div'),name=document.createElement('strong'),hint=document.createElement('small');name.textContent=record.name||'未命名设备';hint.textContent=record.local?'这台电脑':'已保存设备';label.append(name,hint);nameCell.append(makeIcon('monitor'),label);const code=document.createElement('span');code.className='code';code.textContent=record.local&&!local?.code?'正在分配':formatted(record.displayCode||statuses.get(record.deviceID)?.deviceCode||record.deviceID);const statusCell=document.createElement('span');statusCell.dataset.presenceId=record.deviceID;const actions=document.createElement('div');actions.className='device-actions';if(!record.local){const connect=document.createElement('button');connect.type='button';connect.textContent='连接';connect.onclick=()=>selectDevice(record.displayCode||statuses.get(record.deviceID)?.deviceCode||record.deviceID);const remove=document.createElement('button');remove.type='button';remove.textContent='移除';remove.onclick=async()=>{try{await request('/api/local/device/remove',{code:record.deviceID});await loadDevices();}catch(error){notice(error.message);}};actions.append(connect,remove);}else{actions.textContent='本机';actions.classList.add('subtle');}row.append(nameCell,code,statusCell,actions);fragment.append(row);}$('deviceRows').replaceChildren(fragment);$('deviceCount').textContent=String(data.length);const recent=document.createDocumentFragment();for(const record of records.slice(0,3)){const button=document.createElement('button');button.className='recent-card';const label=document.createElement('div'),name=document.createElement('strong'),code=document.createElement('small'),dot=document.createElement('span');name.textContent=record.name||'远程设备';code.textContent=formatted(record.displayCode||statuses.get(record.deviceID)?.deviceCode||record.deviceID);dot.className='dot';dot.dataset.dotId=record.deviceID;label.append(name,code);button.append(makeIcon('monitor'),label,dot);button.onclick=()=>selectDevice(record.displayCode||statuses.get(record.deviceID)?.deviceCode||record.deviceID);recent.append(button);}if(!records.length){const empty=document.createElement('p');empty.className='empty';empty.textContent='连接过的设备会显示在这里，也可在设备列表中手动添加。';recent.append(empty);}$('recentList').replaceChildren(recent);filterDevices();updateBadges();}
function filterDevices(){const needle=normalized($('deviceSearch').value).toLowerCase(),rows=[...document.querySelectorAll('.device-row')],matched=rows.filter(row=>row.dataset.search.replace(/\s/g,'').includes(needle)),size=Math.max(1,Math.min(6,Math.floor((innerHeight-(innerWidth<=500?290:240))/49))),pages=Math.max(1,Math.ceil(matched.length/size));devicePage=Math.min(devicePage,pages-1);const selected=new Set(matched.slice(devicePage*size,(devicePage+1)*size));for(const row of rows)row.hidden=!selected.has(row);$('emptyDevices').hidden=matched.length>0;$('devicePrev').disabled=devicePage===0;$('deviceNext').disabled=devicePage>=pages-1;$('devicePageInfo').textContent=(devicePage+1)+' / '+pages+' · 共 '+matched.length+' 台';}
$('deviceSearch').oninput=()=>{devicePage=0;filterDevices();};
$('devicePrev').onclick=()=>{devicePage=Math.max(0,devicePage-1);filterDevices();};$('deviceNext').onclick=()=>{devicePage++;filterDevices();};window.addEventListener('resize',filterDevices);
async function loadDevices(){try{const result=await request('/api/devices');updateLocal(result.local);records=result.devices||[];renderDevices();await refreshStatuses();}catch(error){notice(error.message);}}
async function queryStatuses(ids){const unique=[...new Set(ids.filter(validCode))];if(!unique.length)return [];const result=await request('/api/device/status',undefined,{ids:unique.join(',')});return result.devices||[];}
async function refreshStatuses(){try{for(const status of await queryStatuses(records.map(r=>r.deviceID)))statuses.set(status.id,status);renderDevices();updateBadges();}catch(_){for(const r of records)statuses.delete(r.deviceID);updateBadges();}}
$('refreshDevices').onclick=loadDevices;loadDevices();setInterval(()=>{loadDevices();if(validCode(normalized($('targetCode').value)))scheduleCheck(0);},30000);
$('addDevice').onclick=()=>{$('addName').value='';$('addCode').value='';$('addDialog').showModal();};$('cancelAdd').onclick=()=>$('addDialog').close();$('addForm').onsubmit=async event=>{event.preventDefault();try{await request('/api/local/device/add',{code:normalized($('addCode').value),name:$('addName').value});$('addDialog').close();await loadDevices();}catch(error){notice(error.message);}};
function targetStatus(text,color=''){$('targetStatus').textContent=text;$('targetStatus').className='presence '+color;}
function scheduleCheck(delay=350){const seq=++checkSequence;clearTimeout(checkTimer);const id=normalized($('targetCode').value);targetStatus(validCode(id)?'检测中…':'输入 9 位设备码检测在线状态');if(!validCode(id))return;checkTimer=setTimeout(async()=>{try{const response=await queryStatuses([id]);if(seq!==checkSequence||id!==normalized($('targetCode').value))return;const found=response.find(s=>s.id===id);statuses.set(id,found);const [text,color]=state(found);targetStatus(text,color==='good'?'online':'offline');}catch(_){if(seq===checkSequence)targetStatus('无法检测，请检查网络','offline');}},delay);}
$('targetCode').oninput=()=>{const value=normalized($('targetCode').value);if(/^\d{0,9}$/.test(value))$('targetCode').value=value.replace(/(\d{3})(?=\d)/g,'$1 ');scheduleCheck();};
$('targetCode').addEventListener('paste',event=>{const text=event.clipboardData?.getData('text')||'',code=text.match(/设备码[：:]\s*([\d ]{9,11})/),pin=text.match(/PIN[：:]\s*(\d{6})/i);if(code&&pin){event.preventDefault();$('targetCode').value=formatted(normalized(code[1]));$('targetPIN').value=pin[1];scheduleCheck();}});
$('connectForm').onsubmit=async event=>{event.preventDefault();if(submitting)return;const id=normalized($('targetCode').value);if(!validCode(id)){notice('请输入 9 位数字设备码');return;}if(local&&(id===local.code||id===local.id)){notice('不能连接本机，请输入另一台设备的设备码');return;}if($('targetPIN').value&&!/^\d{6}$/.test($('targetPIN').value)){notice('请输入对方的 6 位 PIN');return;}submitting=true;$('connectButton').disabled=true;try{const rows=await queryStatuses([id]);if(id!==normalized($('targetCode').value))throw Error('设备码已改变，请重新连接');const s=rows.find(row=>row.id===id);if(!s||!s.online)throw Error('设备离线，请先在对方电脑打开 YuDesk');if(s.connected)throw Error('对方设备已有连接');if(!s.active)throw Error('对方设备尚未激活');if(s.ready===false)throw Error('对方正在准备通道，请稍后重试');$('targetCode').value=id;HTMLFormElement.prototype.submit.call(event.target);}catch(error){notice(error.message);submitting=false;$('connectButton').disabled=false;}};
if($('targetCode').value)scheduleCheck(0);
let serviceBusy=false,setupPrompted=false,serviceSnapshot=null,preferredMode='installed';
try{if(localStorage.getItem('yudesk.runMode')==='portable')preferredMode='portable';}catch(_){}
$('runMode').value=preferredMode;
function rememberMode(mode){preferredMode=mode;$('runMode').value=mode;try{localStorage.setItem('yudesk.runMode',mode);}catch(_){}}
async function serviceStatus(){try{const s=await request('/api/local/service/status');serviceSnapshot=s;$('windowsService').hidden=!s.supported;$('serviceStatus').textContent=s.message;$('installService').textContent=s.updateRequired?'更新并启用当前版本':s.installed?'修复 / 更新安装版':'安装并启用';$('restartInstalled').hidden=!s.installed||s.trustedClient||s.updateRequired||!s.running;$('removeService').hidden=!s.installed;
if(s.packageManaged){$('serviceTitle').textContent='安装与运行';$('serviceDescription').textContent=s.platform==='darwin'?'默认使用 macOS 安装包，安装到“应用程序”。更新时重新运行安装包；屏幕录制与辅助功能仍需本机明确授权。':'默认使用 Linux 安装包，通过软件安装器安装或更新。适用 Debian 12+ / Ubuntu 22.04+；屏幕共享与输入仍受桌面权限限制。';$('installService').hidden=true;$('restartInstalled').hidden=true;$('removeService').hidden=true;$('runMode').value='installed';$('runMode').disabled=true;return;}
if(s.supported&&!s.trustedClient&&!setupPrompted&&!serviceBusy&&preferredMode==='installed'&&document.body.dataset.installPrompt==='true'){setupPrompted=true;await serviceAction(s.installed&&!s.updateRequired&&s.running?'restart':'install',true);}
}catch(_){}finally{setTimeout(serviceStatus,3000);}}
serviceStatus();
async function serviceAction(action,confirmed=false){if(serviceBusy)return;if(action==='remove'&&!confirmed&&!await window.yudeskConfirm('卸载桌面服务后，将无法远程操作 Windows 锁屏界面。继续？'))return;serviceBusy=true;const buttons=['installService','removeService','restartInstalled','runMode'];for(const id of buttons)$(id).disabled=true;$('serviceAction').textContent=action==='restart'?'正在切换到当前安装版…':action==='install'?'正在启动系统管理员授权并安装…':'正在卸载桌面服务…';try{const submit=async value=>{const response=await fetch(endpoint('/api/local/service/'+value),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmed:true}),signal:AbortSignal.timeout(185000)});if(!response.ok)throw Error((await response.text()).slice(0,300));};await submit(action);if(action==='remove'){rememberMode('portable');$('serviceAction').textContent='桌面服务已卸载。';}else{rememberMode('installed');if(action==='install'){const s=await request('/api/local/service/status');if(!s.installed||s.updateRequired||!s.running)throw Error('安装版本尚未就绪，请检查后重试');if(!s.trustedClient){$('serviceAction').textContent='安装成功，正在切换到当前安装版…';await submit('restart');}else $('serviceAction').textContent='安装版已更新并启用。';}else $('serviceAction').textContent='正在打开当前安装版，请稍候。';}}catch(e){$('serviceAction').textContent='操作未完成：'+e.message;}finally{serviceBusy=false;for(const id of buttons)$(id).disabled=false;}}
$('runMode').onchange=async()=>{rememberMode($('runMode').value);if(preferredMode==='installed'&&serviceSnapshot&&!serviceSnapshot.trustedClient)await serviceAction(serviceSnapshot.installed&&!serviceSnapshot.updateRequired&&serviceSnapshot.running?'restart':'install');};
$('installService').onclick=()=>serviceAction('install');$('removeService').onclick=()=>serviceAction('remove');$('restartInstalled').onclick=()=>serviceAction('restart');
