'use strict';
const $=id=>document.getElementById(id),token=document.body.dataset.token;
const endpoint=(path,params={})=>{const u=new URL(path,location.href);u.searchParams.set('access_token',token);for(const [k,v] of Object.entries(params))u.searchParams.set(k,v);return u.href;};
const normalized=value=>value.replace(/\s/g,'').toUpperCase();
const validCode=value=>/^[1-9]\d{8}$/.test(value)||/^[A-F0-9]{24}$/.test(value);
const formatted=value=>/^\d{9}$/.test(value)?value.replace(/(\d{3})(?=\d)/g,'$1 '):value;
let local=null,records=[],signature='',revealPIN=true,checkSequence=0,checkTimer,submitting=false;
let devicePage=0;
let pendingPIN='',pinRotating=false,pinRequest=0;
let meetingSubmitting=false,meetingUntil=0,conference=null;
const statuses=new Map();
const conferenceSpeaker=document.createElement('button');conferenceSpeaker.id='conferenceSpeaker';conferenceSpeaker.type='button';conferenceSpeaker.setAttribute('aria-pressed','true');conferenceSpeaker.innerHTML='<svg viewBox="0 0 24 24"><path d="M4 9h4l5-4v14l-5-4H4Z"/><path d="M16 9a5 5 0 0 1 0 6m2-9a9 9 0 0 1 0 12"/></svg><small>关闭声音</small>';$('conferenceMic').after(conferenceSpeaker);
const conferenceAudioSettings=document.createElement('button');conferenceAudioSettings.id='conferenceAudioSettings';conferenceAudioSettings.type='button';conferenceAudioSettings.innerHTML='<svg><use href="#settings"/></svg><small>声音设备</small>';conferenceSpeaker.after(conferenceAudioSettings);
const conferenceAudioPanel=document.createElement('aside');conferenceAudioPanel.id='conferenceAudioPanel';conferenceAudioPanel.className='conference-audio-panel';conferenceAudioPanel.hidden=true;conferenceAudioPanel.innerHTML='<header><strong>声音设备</strong><button id="conferenceAudioClose" type="button" aria-label="关闭声音设置">×</button></header><div class="conference-audio-section"><span>麦克风电平</span><div class="conference-mic-meter"><i id="conferenceMicLevel"></i></div></div><div class="conference-audio-section"><span>扬声器</span><div id="conferenceOutputList" class="conference-output-list"></div></div><button id="conferenceTestSpeaker" class="conference-test-speaker" type="button">播放测试音</button><p id="conferenceAudioStatus">等待接收其他成员声音</p>';$('conferenceRoom').append(conferenceAudioPanel);
function notice(message){$('notice').textContent=message;$('notice').hidden=!message;}
async function request(path,data,params){const r=await fetch(endpoint(path,params),{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data),cache:'no-store',signal:AbortSignal.timeout(path.includes('activate')?20000:6000)});if(!r.ok)throw Error((await r.text()).slice(0,300));return r.json();}
function tab(name){for(const pane of document.querySelectorAll('.pane'))pane.hidden=pane.id!=='pane-'+name;for(const button of document.querySelectorAll('nav [data-tab]'))button.classList.toggle('selected',button.dataset.tab===name);$('pageTitle').textContent=({remote:'远程控制',meeting:'会议',devices:'设备列表',files:'文件传输',settings:'设置'})[name];if(name==='devices')loadDevices();}
for(const button of document.querySelectorAll('[data-tab]'))button.onclick=()=>tab(button.dataset.tab);
$('homeBrand').onclick=event=>{event.preventDefault();tab('remote');};
fetch(endpoint('/api/ui/watch')).catch(()=>{});
function updateLocal(s){if(local&&(s.pinRevision||0)<(local.pinRevision||0))s={...s,pin:local.pin,pinSynced:local.pinSynced,pinRevision:local.pinRevision};local=s;$('sidebarName').textContent=s.name;$('localName').textContent=s.name;$('localCode').textContent=s.code?formatted(s.code):'正在分配';$('localPIN').textContent=revealPIN?s.pin:'••••••';$('receiving').checked=s.receiving;$('filePermission').checked=s.files;$('receiveDirectory').textContent=s.fileDirectory;$('licenseLabel').textContent='设备授权：'+s.activeUntil;$('serverDot').classList.toggle('online',s.online);$('serverState').textContent=s.online?'服务器已连接':'连接服务器中';$('localState').textContent=!s.receiving?'已暂停接入':s.connected?'连接中':!s.online?'正在连接':s.active?'在线待连接':'等待激活';$('localState').className='badge '+(!s.receiving?'neutral':s.connected||s.online&&s.active?'good':'warning');$('copyCode').disabled=!s.code;$('copyBoth').disabled=!s.code;if(s.code)statuses.set(s.code,{online:s.online,connected:s.connected,active:s.active,ready:s.active&&s.online&&s.receiving&&!s.connected});updateMeeting(s);updateBadges();}
async function refreshLocal(){const generation=pinRequest;try{const value=await request('/api/local/status');if(generation===pinRequest&&!pinRotating)updateLocal(value);if(pendingPIN&&value.pin===pendingPIN&&value.pinSynced){pendingPIN='';notice('PIN 已更换并同步后台，旧 PIN 已失效');}}catch(_){}setTimeout(refreshLocal,2000);}
refreshLocal();
$('rotatePIN').onclick=async()=>{if(pinRotating)return;pinRotating=true;pinRequest++;const button=$('rotatePIN');button.disabled=true;try{await request('/api/local/pin/rotate',{});const value=await request('/api/local/status');pendingPIN=value.pin;updateLocal(value);notice(value.pinSynced?'PIN 已更换并同步后台，旧 PIN 已失效':'PIN 已更换，旧 PIN 已失效；正在同步后台…');if(value.pinSynced)pendingPIN='';}catch(error){notice('更换结果未确认，请核对当前 PIN：'+error.message);}finally{pinRotating=false;button.disabled=false;pinRequest++;}};
async function copy(value,label){if(!value)return;try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(value);else{const area=document.createElement('textarea');area.value=value;area.style.cssText='position:fixed;opacity:0';document.body.append(area);area.select();const copied=document.execCommand('copy');area.remove();if(!copied)throw Error('copy');}notice(label+'已复制');}catch(_){notice('复制失败，请手动选择复制');}}
$('copyCode').onclick=()=>copy(local?.code,'设备码');$('copyPIN').onclick=()=>copy(local?.pin,'PIN');$('copyBoth').onclick=()=>copy(local?.code?'设备码：'+local.code+'\nPIN：'+local.pin:'','设备码和 PIN');$('togglePIN').onclick=()=>{revealPIN=!revealPIN;if(local)updateLocal(local);};
function formatMeeting(value){return value.replace(/\D/g,'').slice(0,9).replace(/(\d{3})(?=\d)/g,'$1 ');}
function updateMeeting(s){const active=!!s.meeting&&/^[1-9]\d{8}$/.test(s.meetingCode||'')&&Date.parse(s.meetingUntil)>Date.now();$('meetingIdle').hidden=active;$('meetingActive').hidden=!active;$('meetingDot').hidden=!active;meetingUntil=active?Date.parse(s.meetingUntil):0;if(active){$('meetingCode').textContent=formatMeeting(s.meetingCode);$('copyMeeting').dataset.code=s.meetingCode;$('enterMeeting').dataset.code=s.meetingCode;}else{$('meetingCode').textContent='—';$('copyMeeting').dataset.code='';$('enterMeeting').dataset.code='';}}
function refreshMeetingCountdown(){if(!meetingUntil){$('meetingCountdown').textContent='—';return;}const seconds=Math.max(0,Math.ceil((meetingUntil-Date.now())/1000)),hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60);$('meetingCountdown').textContent=seconds<=0?'已到期':'剩余 '+(hours?hours+'小时 ':'')+(minutes||!hours?minutes+'分':'');}
setInterval(refreshMeetingCountdown,1000);refreshMeetingCountdown();
$('meetingHostName').value=$('meetingJoinName').value=(()=>{try{return localStorage.getItem('yudesk.meetingName')||'';}catch(_){return '';}})();
function rememberMeetingName(value){value=value.trim();$('meetingHostName').value=value;$('meetingJoinName').value=value;try{localStorage.setItem('yudesk.meetingName',value);}catch(_){}return value;}
function validMeetingName(value){return value.length>0&&[...value].length<=32&&!/[\u0000-\u001f\u007f]/.test(value);}
for(const id of ['meetingHostName','meetingJoinName'])$(id).onchange=()=>rememberMeetingName($(id).value);
async function prepareConferenceMedia(microphone,camera){if(!microphone&&!camera)return new MediaStream();if(!navigator.mediaDevices?.getUserMedia)throw Error('当前系统浏览器不支持麦克风或摄像头，请更新系统组件');try{return await navigator.mediaDevices.getUserMedia({audio:microphone?{echoCancellation:true,noiseSuppression:true,autoGainControl:true}:false,video:camera?{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:24,max:30},facingMode:'user'}:false});}catch(error){throw Error('未取得麦克风或摄像头权限，请在系统提示中允许后重试');}}
$('startMeeting').onclick=async()=>{if(meetingSubmitting)return;const name=rememberMeetingName($('meetingHostName').value);if(!validMeetingName(name)){notice('请输入 1 到 32 个字符的姓名');return;}meetingSubmitting=true;const button=$('startMeeting');button.disabled=true;let stream;try{stream=await prepareConferenceMedia($('meetingHostMic').checked,$('meetingHostCamera').checked);await request('/api/local/meeting/start',{});const value=await request('/api/local/status');updateLocal(value);await enterConference(value.meetingCode,true,name,stream);notice('会议已创建，你已作为主持人进入');}catch(error){if(stream)for(const track of stream.getTracks())track.stop();notice(error.message);}finally{meetingSubmitting=false;button.disabled=false;}};
$('enterMeeting').onclick=async()=>{const name=rememberMeetingName($('meetingHostName').value);if(!validMeetingName(name)){notice('请输入姓名后再进入会议');$('meetingHostName').focus();return;}let stream;try{stream=await prepareConferenceMedia($('meetingHostMic').checked,$('meetingHostCamera').checked);await enterConference($('enterMeeting').dataset.code,true,name,stream);}catch(error){if(stream)for(const track of stream.getTracks())track.stop();notice(error.message);}};
$('copyMeeting').onclick=()=>{const code=$('copyMeeting').dataset.code;if(code)copy('YuDesk 会议号：'+formatMeeting(code)+'\n填写姓名和会议号即可直接加入','会议号');};
$('endMeeting').onclick=async()=>{if(!await window.yudeskConfirm('结束本次会议？会议号会立即失效，已加入的参与者也会断开。'))return;const button=$('endMeeting');button.disabled=true;try{await request('/api/local/meeting/end',{});updateLocal(await request('/api/local/status'));notice('会议已结束，原会议号已失效');}catch(error){notice(error.message);}finally{button.disabled=false;}};
function meetingParts(){const value=$('meetingInvite').value.replace(/\D/g,'');return /^[1-9]\d{8}$/.test(value)?{code:value}:null;}
let meetingCheckSequence=0,meetingCheckTimer;
function checkMeeting(delay=350){const seq=++meetingCheckSequence;clearTimeout(meetingCheckTimer);const parts=meetingParts();$('meetingStatus').className='presence';$('meetingStatus').textContent=parts?'查询会议状态…':'输入正确会议号即可直接加入';if(!parts)return;meetingCheckTimer=setTimeout(async()=>{try{await request('/api/local/meeting/resolve',undefined,{code:parts.code});if(seq!==meetingCheckSequence)return;$('meetingStatus').textContent='会议进行中 · 最多 8 人 · 可以直接加入';$('meetingStatus').className='presence online';}catch(_){if(seq===meetingCheckSequence){$('meetingStatus').textContent='会议不存在、已结束或已过期';$('meetingStatus').className='presence offline';}}},delay);}
$('meetingInvite').oninput=()=>{$('meetingInvite').value=formatMeeting($('meetingInvite').value);checkMeeting();};
$('meetingInvite').addEventListener('paste',event=>{const text=event.clipboardData?.getData('text')||'',digits=text.replace(/\D/g,'');if(digits.length===9){event.preventDefault();$('meetingInvite').value=formatMeeting(digits);checkMeeting(0);}});
$('meetingJoinForm').onsubmit=async event=>{event.preventDefault();if(meetingSubmitting)return;const parts=meetingParts(),name=rememberMeetingName($('meetingJoinName').value);if(!validMeetingName(name)){notice('请输入 1 到 32 个字符的姓名');return;}if(!parts){notice('请输入 9 位会议号');return;}meetingSubmitting=true;$('joinMeeting').disabled=true;let stream;try{await request('/api/local/meeting/resolve',undefined,{code:parts.code});stream=await prepareConferenceMedia($('meetingJoinMic').checked,$('meetingJoinCamera').checked);await enterConference(parts.code,false,name,stream);}catch(error){if(stream)for(const track of stream.getTracks())track.stop();notice(error.message);}finally{meetingSubmitting=false;$('joinMeeting').disabled=false;}};
function conferenceSocketURL(code,name,host){const u=new URL('/api/local/conference',location.href);u.protocol=u.protocol==='https:'?'wss:':'ws:';u.searchParams.set('access_token',token);u.searchParams.set('code',code);u.searchParams.set('name',name);if(host)u.searchParams.set('host','1');return u.href;}
$('conferenceCopy').onclick=()=>{if(conference)copy('YuDesk 会议号：'+formatMeeting(conference.code)+'\n填写姓名和会议号即可直接加入','会议号');};
async function enterConference(code,requestedHost,name,stream){if(conference)await leaveConference(false,false);let savedOutput='default';try{savedOutput=localStorage.getItem('yudesk.meetingOutput')||'default';}catch(_){}const active=conference={code,name,requestedHost,stream,screen:null,speaker:true,audioBlocked:false,outputID:savedOutput,audioElements:new Map(),micMonitor:null,ws:null,selfID:'',hostID:'',peers:new Map(),states:new Map(),tiles:new Map(),intentional:false,heartbeat:0,recording:null,recordingFrame:0,rtc:conferenceICEPolicy()};document.body.classList.add('conference-live');$('conferenceRoom').hidden=false;$('conferenceTitle').textContent='YuDesk 会议';$('conferenceCode').textContent=formatMeeting(code);$('conferenceConnection').textContent='正在安全进入会议…';$('conferenceMembers').hidden=true;active.states.set('local',{id:'local',name,microphone:stream.getAudioTracks().some(t=>t.enabled),camera:stream.getVideoTracks().some(t=>t.enabled),screen:false,recording:false});ensureConferenceTile('local',name,true,stream);startConferenceMicMeter(active);renderConferenceMembers();updateConferenceControls();await new Promise((resolve,reject)=>{const ws=new WebSocket(conferenceSocketURL(code,name,requestedHost));active.ws=ws;let welcomed=false,settled=false;const fail=message=>{if(settled)return;settled=true;reject(Error(message));};const timeout=setTimeout(()=>{active.intentional=true;if(conference===active){conference=null;cleanupConference(active);}ws.close();fail('进入会议超时，请检查网络后重试');},12000);ws.onopen=()=>{if(conference===active)$('conferenceConnection').textContent='正在同步参会成员…';};ws.onmessage=async event=>{if(conference!==active)return;let message;try{message=JSON.parse(event.data);}catch(_){return;}try{await handleConferenceMessage(message,active);if(message.type==='welcome'&&!settled){welcomed=true;settled=true;clearTimeout(timeout);resolve();}}catch(error){notice(error.message);}};ws.onerror=()=>{};ws.onclose=event=>{clearTimeout(timeout);if(conference!==active||active.intentional)return;conference=null;cleanupConference(active);const message=welcomed?'会议连接已断开，请重新进入':'无法进入会议，请确认会议号、设备授权和网络状态';if(!settled)fail(message);else notice(message);};});if(conference!==active)return;active.heartbeat=setInterval(()=>active.ws?.readyState===WebSocket.OPEN&&active.ws.send(JSON.stringify({type:'ping'})),15000);sendConferenceState();}
function playConferenceMedia(video,isLocal){if(!conference)return;video.volume=1;video.muted=true;const playing=video.play();if(playing?.catch)playing.catch(()=>{});}
function conferenceAudioKey(peerID,track){return peerID+':'+track.id;}
function refreshConferenceAudioStatus(){if(!conference)return;const tracks=[...conference.audioElements.values()].filter(item=>item.track.readyState==='live'),playing=tracks.filter(item=>!item.audio.paused&&!item.audio.muted);$('conferenceAudioStatus').textContent=!tracks.length?'等待接收其他成员声音':conference.speaker?(playing.length+' / '+tracks.length+' 路声音正在播放'):'已关闭会议声音';}
async function applyConferenceOutput(audio,active=conference){if(!active||typeof audio.setSinkId!=='function')return;try{await audio.setSinkId(active.outputID||'default');}catch(error){active.outputID='default';await audio.setSinkId('default').catch(()=>{});notice('所选扬声器不可用，已切换到系统默认设备');}}
function playConferenceAudio(audio,active=conference){if(!active||conference!==active)return;audio.volume=1;audio.muted=!active.speaker;applyConferenceOutput(audio,active).then(()=>{if(!active.speaker)return;const playing=audio.play();if(playing?.catch)playing.catch(error=>{if(conference!==active)return;active.audioBlocked=true;refreshConferenceAudioStatus();notice(error?.name==='NotAllowedError'?'系统已阻止自动播放，请点击“播放声音”':'会议声音播放失败，请打开“声音设备”检测扬声器');});}).finally(refreshConferenceAudioStatus);}
function removeConferenceAudio(peerID,track){const active=conference,key=conferenceAudioKey(peerID,track),item=active?.audioElements.get(key);if(!item)return;item.audio.pause();item.audio.srcObject=null;item.audio.remove();active.audioElements.delete(key);refreshConferenceAudioStatus();}
function syncConferenceAudioTrack(peerID,track){const active=conference;if(!active||track.kind!=='audio')return;const key=conferenceAudioKey(peerID,track);if(active.audioElements.has(key)){playConferenceAudio(active.audioElements.get(key).audio,active);return;}const audio=document.createElement('audio');audio.className='conference-remote-audio';audio.autoplay=true;audio.playsInline=true;audio.srcObject=new MediaStream([track]);audio.onplaying=refreshConferenceAudioStatus;audio.onpause=refreshConferenceAudioStatus;audio.onerror=()=>{if(conference===active)notice('收到声音数据，但扬声器播放失败，请打开“声音设备”检查');};$('conferenceRoom').append(audio);active.audioElements.set(key,{audio,track,peerID});playConferenceAudio(audio,active);refreshConferenceAudioStatus();}
function stopConferenceMicMeter(active){const monitor=active?.micMonitor;if(!monitor)return;cancelAnimationFrame(monitor.frame);monitor.source?.disconnect();monitor.context?.close().catch(()=>{});active.micMonitor=null;if(conference===active&&$('conferenceMicLevel'))$('conferenceMicLevel').style.width='0%';}
function startConferenceMicMeter(active=conference){if(!active)return;stopConferenceMicMeter(active);const track=active.stream?.getAudioTracks().find(item=>item.readyState==='live');if(!track)return;try{const context=new AudioContext(),source=context.createMediaStreamSource(new MediaStream([track])),analyser=context.createAnalyser(),values=new Uint8Array(256),monitor={context,source,analyser,values,frame:0,last:0};analyser.fftSize=512;source.connect(analyser);active.micMonitor=monitor;const draw=time=>{if(conference!==active||active.micMonitor!==monitor)return;monitor.frame=requestAnimationFrame(draw);if(time-monitor.last<80)return;monitor.last=time;analyser.getByteTimeDomainData(values);let peak=0;for(const value of values)peak=Math.max(peak,Math.abs(value-128));const level=Math.min(100,Math.round(peak/36*100));$('conferenceMicLevel').style.width=(track.enabled?level:0)+'%';};context.resume().catch(()=>{});monitor.frame=requestAnimationFrame(draw);}catch(_){}}
async function refreshConferenceOutputs(){if(!conference)return;const list=$('conferenceOutputList');list.replaceChildren();let devices=[];try{devices=(await navigator.mediaDevices.enumerateDevices()).filter(device=>device.kind==='audiooutput');}catch(_){}if(!devices.length)devices=[{deviceId:'default',label:'系统默认扬声器'}];for(const [index,device] of devices.entries()){const button=document.createElement('button');button.type='button';button.dataset.device=device.deviceId;button.className=device.deviceId===conference.outputID?'selected':'';button.textContent=device.label||('扬声器 '+(index+1));button.onclick=()=>selectConferenceOutput(device.deviceId);list.append(button);}}
async function selectConferenceOutput(deviceID){if(!conference)return;conference.outputID=deviceID||'default';try{localStorage.setItem('yudesk.meetingOutput',conference.outputID);}catch(_){}for(const item of conference.audioElements.values())await applyConferenceOutput(item.audio);await refreshConferenceOutputs();refreshConferenceAudioStatus();notice('会议声音已切换到所选扬声器');}
function ensureConferenceTile(id,name,isLocal=false,stream=null){if(!conference)return null;let tile=conference.tiles.get(id);if(!tile){tile=document.createElement('article');tile.className='conference-tile'+(isLocal?' local':'');tile.dataset.id=id;const video=document.createElement('video');video.autoplay=true;video.playsInline=true;video.muted=isLocal;const avatar=document.createElement('div');avatar.className='conference-avatar';avatar.textContent=([...name][0]||'参').toUpperCase();const label=document.createElement('span');label.className='conference-tile-name';label.textContent=name+(isLocal?'（我）':'');const state=document.createElement('span');state.className='conference-tile-state';tile.append(video,avatar,label,state);$('conferenceGrid').append(tile);conference.tiles.set(id,tile);}if(stream){const video=tile.querySelector('video');if(video.srcObject!==stream)video.srcObject=stream;playConferenceMedia(video,isLocal);const hasVideo=stream.getVideoTracks().some(track=>track.readyState==='live'&&track.enabled);tile.classList.toggle('has-video',hasVideo);syncConferenceRecordingAudio();}return tile;}
function updateConferenceTile(id){if(!conference)return;const state=conference.states.get(id),tile=conference.tiles.get(id==='local'?'local':id);if(!state||!tile)return;tile.querySelector('.conference-tile-name').textContent=state.name+((id==='local'||id===conference.selfID)?'（我）':'')+(id===conference.hostID?' · 主持人':'');tile.querySelector('.conference-tile-state').innerHTML='<span class="'+(state.microphone?'active':'')+'">'+(state.microphone?'麦克风':'静音')+'</span>'+(state.screen?'<span class="active">共享</span>':state.camera?'<span class="active">视频</span>':'');const video=tile.querySelector('video'),stream=video.srcObject;tile.classList.toggle('has-video',!!stream&&stream.getVideoTracks().some(track=>track.readyState==='live'&&track.enabled)&&(state.camera||state.screen));}
function peerState(peer){return {id:peer.id,name:peer.name||'参会者',microphone:!!peer.microphone,camera:!!peer.camera,screen:!!peer.screen,recording:!!peer.recording};}
async function handleConferenceMessage(message,active=conference){if(!conference||conference!==active)return;if(message.type==='welcome'){active.selfID=message.id;active.hostID=message.host;active.rtc=conferenceICEPolicy(message.rtc);const localState=active.states.get('local');active.states.delete('local');localState.id=message.id;active.states.set(message.id,localState);const localTile=active.tiles.get('local');active.tiles.delete('local');localTile.dataset.id=message.id;active.tiles.set(message.id,localTile);let mediaFailure=false;for(const peer of message.peers||[]){active.states.set(peer.id,peerState(peer));ensureConferenceTile(peer.id,peer.name);try{await createConferencePeer(peer.id,true);}catch(_){mediaFailure=true;}}$('conferenceConnection').textContent=mediaFailure?'部分成员媒体连接失败':(active.peers.size?'正在直连音视频…':'等待其他成员');renderConferenceMembers();updateConferenceControls();sendConferenceState();return;}if(message.type==='peer-joined'){active.states.set(message.id,{id:message.id,name:message.name||'参会者',microphone:false,camera:false,screen:false,recording:false});ensureConferenceTile(message.id,message.name||'参会者');renderConferenceMembers();renderConferenceConnection();return;}if(message.type==='peer-left'){removeConferencePeer(message.id);return;}if(message.type==='state'){const state=active.states.get(message.id);if(state){Object.assign(state,{microphone:!!message.microphone,camera:!!message.camera,screen:!!message.screen,recording:!!message.recording});updateConferenceTile(message.id);renderConferenceMembers();updateConferenceRecordingBadge();}return;}if(message.type==='host'){const wasHost=active.hostID===active.selfID;active.hostID=message.host;if(wasHost&&active.hostID!==active.selfID){if(active.screen)await stopConferenceShare();if(active.recording)stopConferenceRecording(active);}renderConferenceMembers();updateConferenceControls();for(const id of active.states.keys())updateConferenceTile(id);return;}if(message.type==='signal'){await receiveConferenceSignal(message);return;}if(message.type==='ended'){const ownsRoom=active.requestedHost&&local?.meetingCode===active.code;conference=null;cleanupConference(active);if(ownsRoom)request('/api/local/meeting/end',{}).catch(()=>{});notice(message.message||'会议已结束');return;}}
function sendConference(message){if(conference?.ws?.readyState===WebSocket.OPEN)conference.ws.send(JSON.stringify(message));}
function sendConferenceState(){if(!conference||!conference.selfID)return;const state=conference.states.get(conference.selfID);if(state)sendConference({type:'state',microphone:state.microphone,camera:state.camera,screen:state.screen,recording:state.recording});updateConferenceTile(conference.selfID);updateConferenceControls();updateConferenceRecordingBadge();}
function conferenceICEPolicy(raw){const fallback={iceServers:[{urls:['stun:www.yucg.cn:8233']}],directTimeoutMs:3000,relayEnabled:false};if(!raw||typeof raw!=='object')return fallback;const servers=[];for(const source of Array.isArray(raw.iceServers)?raw.iceServers.slice(0,16):[]){const urls=(Array.isArray(source?.urls)?source.urls:[source?.urls]).filter(url=>typeof url==='string'&&url.length<=256&&!/[\r\n\t ]/.test(url)&&/^(stun|turns?):/.test(url)).slice(0,8);if(urls.length)servers.push({urls,username:String(source?.username||''),credential:String(source?.credential||'')});}return {iceServers:servers.length?servers:fallback.iceServers,directTimeoutMs:Math.max(1000,Math.min(30000,Number(raw.directTimeoutMs)||3000)),relayEnabled:servers.some(server=>server.urls.some(url=>/^turns?:/.test(url)))};}
function directConferenceICEServers(policy){return policy.iceServers.map(server=>({...server,urls:server.urls.filter(url=>url.startsWith('stun:'))})).filter(server=>server.urls.length);}
function renderConferenceConnection(){if(!conference)return;if(!conference.peers.size){$('conferenceConnection').textContent='等待其他成员';return;}const paths=[...conference.peers.values()].map(entry=>entry.path||'正在直连');$('conferenceConnection').textContent=paths.includes('中转连接')?'中转连接 · 音视频已加密':paths.every(path=>path==='P2P 直连')?'P2P 直连 · 音视频已加密':paths.includes('网络连接不稳定')?'部分成员网络不稳定':paths.includes('正在连接中转')?'正在连接音视频中转…':'正在直连音视频…';}
async function readConferencePath(id,entry){if(conference?.peers.get(id)!==entry||!['connected','completed'].includes(entry.pc.iceConnectionState)&&entry.pc.connectionState!=='connected')return;try{const report=await entry.pc.getStats();if(conference?.peers.get(id)!==entry)return;let pair;for(const value of report.values())if(value.type==='transport'&&value.selectedCandidatePairId)pair=report.get(value.selectedCandidatePairId);if(!pair)for(const value of report.values())if(value.type==='candidate-pair'&&value.state==='succeeded'&&(value.nominated||value.selected)){pair=value;break;}if(pair){const localCandidate=report.get(pair.localCandidateId),remoteCandidate=report.get(pair.remoteCandidateId);entry.path=localCandidate?.candidateType==='relay'||remoteCandidate?.candidateType==='relay'?'中转连接':'P2P 直连';renderConferenceConnection();}}catch(_){}}
function updateConferencePath(id,entry){if(conference?.peers.get(id)!==entry)return;const connected=['connected','completed'].includes(entry.pc.iceConnectionState)||entry.pc.connectionState==='connected';if(connected){clearTimeout(entry.routeDeadline);clearTimeout(entry.recovery);readConferencePath(id,entry);renderConferenceConnection();return;}if((entry.pc.iceConnectionState==='failed'||entry.pc.connectionState==='failed')&&!entry.relay)fallbackConferencePeer(id,entry);else if(entry.pc.iceConnectionState==='disconnected'&&!entry.recovery){entry.path='正在重连';entry.recovery=setTimeout(()=>{entry.recovery=0;fallbackConferencePeer(id,entry);},3000);}else if(entry.relay&&(entry.pc.iceConnectionState==='failed'||entry.pc.connectionState==='failed'))entry.path='网络连接不稳定';renderConferenceConnection();}
function fallbackConferencePeer(id,entry){if(conference?.peers.get(id)!==entry||['connected','completed'].includes(entry.pc.iceConnectionState)||entry.pc.connectionState==='connected')return;clearTimeout(entry.routeDeadline);if(!conference.rtc.relayEnabled){entry.path='网络连接不稳定';renderConferenceConnection();return;}entry.relay=true;entry.path='正在连接中转';renderConferenceConnection();try{entry.pc.setConfiguration({...entry.pc.getConfiguration(),iceServers:conference.rtc.iceServers,iceTransportPolicy:'all'});entry.pc.restartIce();negotiateConferencePeer(id).catch(()=>{entry.path='网络连接不稳定';renderConferenceConnection();});}catch(_){entry.path='网络连接不稳定';renderConferenceConnection();}}
function closeConferencePeer(entry){clearTimeout(entry?.routeDeadline);clearTimeout(entry?.recovery);clearInterval(entry?.statsTimer);entry?.pc?.close();}
async function createConferencePeer(id,initiator){if(!conference||id===conference.selfID)return null;if(conference.peers.has(id))return conference.peers.get(id);const pc=new RTCPeerConnection({iceServers:directConferenceICEServers(conference.rtc),iceTransportPolicy:'all',bundlePolicy:'max-bundle'}),entry={pc,makingOffer:false,needsNegotiation:false,ignoreOffer:false,pendingCandidates:[],videoSender:null,screenAudioSenders:[],remoteStream:new MediaStream(),dataChannel:null,path:'正在直连',relay:false,recovery:0,routeDeadline:0,statsTimer:0};conference.peers.set(id,entry);for(const track of conference.stream.getTracks()){const sender=pc.addTrack(track,conference.stream);if(track.kind==='video')entry.videoSender=sender;}if(!conference.stream.getAudioTracks().length)pc.addTransceiver('audio',{direction:'recvonly'});if(!conference.stream.getVideoTracks().length)pc.addTransceiver('video',{direction:'recvonly'});if(conference.screen){const screenTrack=conference.screen.getVideoTracks()[0];if(entry.videoSender)await entry.videoSender.replaceTrack(screenTrack);else entry.videoSender=pc.addTrack(screenTrack,conference.screen);for(const track of conference.screen.getAudioTracks())entry.screenAudioSenders.push(pc.addTrack(track,conference.screen));}pc.onicecandidate=event=>{if(event.candidate)sendConference({type:'signal',to:id,signal:'candidate',candidate:JSON.stringify(event.candidate)});};pc.ontrack=event=>{if(!entry.remoteStream.getTracks().some(track=>track.id===event.track.id))entry.remoteStream.addTrack(event.track);const refresh=()=>{if(conference?.peers.get(id)!==entry)return;if(event.track.kind==='audio')syncConferenceAudioTrack(id,event.track);ensureConferenceTile(id,conference.states.get(id)?.name||'参会者',false,entry.remoteStream);updateConferenceTile(id);};refresh();event.track.onunmute=refresh;event.track.onended=()=>{removeConferenceAudio(id,event.track);try{entry.remoteStream.removeTrack(event.track);}catch(_){}refresh();};};pc.ondatachannel=event=>{entry.dataChannel=event.channel;};pc.onconnectionstatechange=()=>updateConferencePath(id,entry);pc.oniceconnectionstatechange=()=>updateConferencePath(id,entry);entry.routeDeadline=setTimeout(()=>fallbackConferencePeer(id,entry),conference.rtc.directTimeoutMs);entry.statsTimer=setInterval(()=>readConferencePath(id,entry),2500);renderConferenceConnection();if(initiator){entry.dataChannel=pc.createDataChannel('yudesk-session');await negotiateConferencePeer(id);}return entry;}
async function negotiateConferencePeer(id){const entry=conference?.peers.get(id);if(!entry)return;entry.needsNegotiation=true;if(entry.makingOffer||entry.pc.signalingState!=='stable')return;try{entry.makingOffer=true;entry.needsNegotiation=false;await entry.pc.setLocalDescription(await entry.pc.createOffer());sendConference({type:'signal',to:id,signal:'offer',sdp:entry.pc.localDescription.sdp});}finally{entry.makingOffer=false;}}
async function receiveConferenceSignal(message){let entry=conference?.peers.get(message.from);if(!entry)entry=await createConferencePeer(message.from,false);if(!entry)return;const pc=entry.pc;if(message.signal==='candidate'){let candidate;try{candidate=JSON.parse(message.candidate);}catch(_){return;}if(!pc.remoteDescription){if(entry.pendingCandidates.length<64)entry.pendingCandidates.push(candidate);return;}try{await pc.addIceCandidate(candidate);}catch(error){if(!entry.ignoreOffer)throw error;}return;}const description={type:message.signal,sdp:message.sdp},collision=description.type==='offer'&&(entry.makingOffer||pc.signalingState!=='stable'),polite=conference.selfID>message.from;entry.ignoreOffer=!polite&&collision;if(entry.ignoreOffer)return;if(collision)await pc.setLocalDescription({type:'rollback'});await pc.setRemoteDescription(description);for(const candidate of entry.pendingCandidates.splice(0)){try{await pc.addIceCandidate(candidate);}catch(error){if(!entry.ignoreOffer)throw error;}}if(description.type==='offer'){await pc.setLocalDescription(await pc.createAnswer());sendConference({type:'signal',to:message.from,signal:'answer',sdp:pc.localDescription.sdp});}if(entry.needsNegotiation)await negotiateConferencePeer(message.from);}
function removeConferencePeer(id){if(!conference)return;closeConferencePeer(conference.peers.get(id));for(const item of [...conference.audioElements.values()])if(item.peerID===id)removeConferenceAudio(id,item.track);conference.peers.delete(id);conference.states.delete(id);conference.tiles.get(id)?.remove();conference.tiles.delete(id);renderConferenceMembers();updateConferenceRecordingBadge();renderConferenceConnection();}
function renderConferenceMembers(){if(!conference)return;const list=document.createDocumentFragment(),states=[...conference.states.values()];for(const state of states){const row=document.createElement('div');row.className='conference-member';const avatar=document.createElement('span');avatar.className='conference-member-avatar';avatar.textContent=([...state.name][0]||'参').toUpperCase();const info=document.createElement('div'),name=document.createElement('strong'),detail=document.createElement('small');name.textContent=state.name+(state.id===conference.selfID?'（我）':'');detail.textContent=(state.id===conference.hostID?'主持人 · ':'')+(state.microphone?'麦克风开启':'已静音')+(state.camera?' · 视频开启':'');info.append(name,detail);row.append(avatar,info);if(conference.selfID===conference.hostID&&state.id!==conference.selfID){const transfer=document.createElement('button');transfer.type='button';transfer.textContent='设为主持人';transfer.onclick=async()=>{if(await window.yudeskConfirm('将主持人转交给“'+state.name+'”？转交后由对方管理共享和结束会议。'))sendConference({type:'transfer',to:state.id});};row.append(transfer);}list.append(row);}$('conferenceMemberList').replaceChildren(list);$('conferenceMemberCount').textContent=states.length+' 人';}
function updateConferenceControls(){if(!conference)return;const state=conference.states.get(conference.selfID)||conference.states.get('local'),isHost=conference.selfID!==''&&conference.hostID===conference.selfID;$('conferenceMic').setAttribute('aria-pressed',String(!!state?.microphone));$('conferenceMic').querySelector('small').textContent=state?.microphone?'静音':'解除静音';conferenceSpeaker.setAttribute('aria-pressed',String(conference.speaker));conferenceSpeaker.querySelector('small').textContent=conference.speaker?'关闭声音':'播放声音';$('conferenceCamera').setAttribute('aria-pressed',String(!!state?.camera));$('conferenceCamera').querySelector('small').textContent=state?.camera?'关闭视频':'开启视频';$('conferenceShare').hidden=!isHost;$('conferenceRecord').hidden=!isHost;$('conferenceLeave').querySelector('small').textContent=isHost?'结束会议':'离开会议';}
async function addConferenceMedia(kind){if(!conference)return null;const media=await navigator.mediaDevices.getUserMedia(kind==='audio'?{audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}}:{video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:24,max:30},facingMode:'user'}}),track=media.getTracks()[0];conference.stream.addTrack(track);for(const [id,entry] of conference.peers){if(kind==='video'&&conference.screen)continue;const sender=entry.pc.addTrack(track,conference.stream);if(kind==='video')entry.videoSender=sender;await negotiateConferencePeer(id);}return track;}
$('conferenceMic').onclick=async()=>{if(!conference)return;let track=conference.stream.getAudioTracks()[0];try{const created=!track;if(created)track=await addConferenceMedia('audio');else track.enabled=!track.enabled;if(created)track.enabled=true;const state=conference.states.get(conference.selfID);state.microphone=track.enabled;startConferenceMicMeter(conference);sendConferenceState();}catch(error){notice('麦克风开启失败：'+error.message);}};
conferenceSpeaker.onclick=()=>{if(!conference)return;conference.speaker=!conference.speaker;conference.audioBlocked=false;for(const item of conference.audioElements.values())playConferenceAudio(item.audio);updateConferenceControls();refreshConferenceAudioStatus();notice(conference.speaker?'会议声音已开启':'会议声音已关闭');};
conferenceAudioSettings.onclick=async()=>{if(!conference)return;conferenceAudioPanel.hidden=!conferenceAudioPanel.hidden;conferenceAudioSettings.setAttribute('aria-pressed',String(!conferenceAudioPanel.hidden));if(!conferenceAudioPanel.hidden)await refreshConferenceOutputs();refreshConferenceAudioStatus();};
$('conferenceAudioClose').onclick=()=>{conferenceAudioPanel.hidden=true;conferenceAudioSettings.setAttribute('aria-pressed','false');};
$('conferenceTestSpeaker').onclick=async()=>{if(!conference)return;const button=$('conferenceTestSpeaker');button.disabled=true;try{const context=new AudioContext();if(typeof context.setSinkId==='function')await context.setSinkId(conference.outputID||'default');await context.resume();const oscillator=context.createOscillator(),gain=context.createGain();oscillator.type='sine';oscillator.frequency.setValueAtTime(660,context.currentTime);oscillator.frequency.setValueAtTime(880,context.currentTime+.18);gain.gain.setValueAtTime(.0001,context.currentTime);gain.gain.exponentialRampToValueAtTime(.09,context.currentTime+.025);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.42);oscillator.connect(gain).connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.45);await new Promise(resolve=>oscillator.onended=resolve);await context.close();notice('测试音已播放；若未听到，请在“声音设备”中切换扬声器');}catch(error){notice('测试音播放失败：'+error.message);}finally{button.disabled=false;}};
$('conferenceCamera').onclick=async()=>{if(!conference)return;let track=conference.stream.getVideoTracks()[0];try{const created=!track;if(created)track=await addConferenceMedia('video');else track.enabled=!track.enabled;if(created)track.enabled=true;const state=conference.states.get(conference.selfID);state.camera=track.enabled;if(!conference.screen)ensureConferenceTile(conference.selfID,state.name,true,conference.stream);sendConferenceState();}catch(error){notice('摄像头开启失败：'+error.message);}};
async function replaceConferenceVideo(track,stream,renegotiate=true){if(!conference)return [];const changed=[];for(const [id,entry] of conference.peers){if(entry.videoSender)await entry.videoSender.replaceTrack(track);else if(track){entry.videoSender=entry.pc.addTrack(track,stream);changed.push(id);}}if(renegotiate)for(const id of changed)await negotiateConferencePeer(id);return changed;}
async function stopConferenceShare(){if(!conference?.screen)return;const screen=conference.screen;conference.screen=null;const changed=new Set();for(const [id,entry] of conference.peers){for(const sender of entry.screenAudioSenders||[])try{entry.pc.removeTrack(sender);}catch(_){}if(entry.screenAudioSenders?.length)changed.add(id);entry.screenAudioSenders=[];}for(const track of screen.getTracks()){track.onended=null;track.stop();}const camera=conference.stream.getVideoTracks()[0]||null;for(const id of await replaceConferenceVideo(camera,conference.stream,false))changed.add(id);for(const id of changed)await negotiateConferencePeer(id);const state=conference.states.get(conference.selfID);state.screen=false;const tile=ensureConferenceTile(conference.selfID,state.name,true,conference.stream);tile.querySelector('video').classList.remove('screen');$('conferenceShare').setAttribute('aria-pressed','false');sendConferenceState();}
function screenShareFailure(error){if(error?.name==='NotAllowedError'||/permission denied|not allowed/i.test(error?.message||''))return '系统未允许共享。请在系统选择窗口中选中屏幕并点击“共享”；取消不会影响会议';if(error?.name==='NotFoundError')return '没有找到可共享的屏幕或窗口';return error?.message||'当前系统无法开始屏幕共享';}
$('conferenceShare').onclick=async()=>{if(!conference||conference.hostID!==conference.selfID)return;try{if(conference.screen){await stopConferenceShare();notice('屏幕共享已停止');return;}if(!navigator.mediaDevices?.getDisplayMedia)throw Error('当前系统组件不支持屏幕共享');const screen=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:20,max:30}},audio:true}),track=screen.getVideoTracks()[0];if(!track)throw Error('没有取得可共享的画面');conference.screen=screen;track.onended=()=>stopConferenceShare().catch(()=>{});const changed=new Set(await replaceConferenceVideo(track,screen,false));for(const [id,entry] of conference.peers){for(const audio of screen.getAudioTracks())entry.screenAudioSenders.push(entry.pc.addTrack(audio,screen));if(screen.getAudioTracks().length)changed.add(id);}for(const id of changed)await negotiateConferencePeer(id);const state=conference.states.get(conference.selfID);state.screen=true;const tile=ensureConferenceTile(conference.selfID,state.name,true,screen);tile.querySelector('video').classList.add('screen');$('conferenceShare').setAttribute('aria-pressed','true');sendConferenceState();notice(screen.getAudioTracks().length?'屏幕和系统声音正在共享':'屏幕正在共享；如需共享电脑声音，请在系统选择窗口勾选“共享音频”');}catch(error){if(conference?.screen)await stopConferenceShare().catch(()=>{});notice('共享屏幕未开启：'+screenShareFailure(error));}};
$('conferenceMemberButton').onclick=()=>{const open=$('conferenceMembers').hidden;$('conferenceMembers').hidden=!open;$('conferenceMemberButton').setAttribute('aria-pressed',String(open));};
function updateConferenceRecordingBadge(){if(!conference)return;const active=[...conference.states.values()].some(state=>state.recording);$('conferenceRecording').hidden=!active;}
function syncConferenceRecordingAudio(){const recording=conference?.recording;if(!recording?.audioContext||!recording.destination)return;for(const tile of conference.tiles.values()){const stream=tile.querySelector('video').srcObject;if(!stream)continue;for(const track of stream.getAudioTracks()){if(recording.audioSources.has(track))continue;try{const sourceStream=new MediaStream([track]),source=recording.audioContext.createMediaStreamSource(sourceStream);source.connect(recording.destination);recording.audioSources.set(track,{source,stream:sourceStream});}catch(_){}}}}
function drawConferenceRecording(){if(!conference?.recording)return;const {canvas,context}=conference.recording,videos=[...document.querySelectorAll('#conferenceGrid video')].filter(video=>video.srcObject);context.fillStyle='#10141c';context.fillRect(0,0,canvas.width,canvas.height);const count=Math.max(1,videos.length),columns=Math.ceil(Math.sqrt(count)),rows=Math.ceil(count/columns),cellW=canvas.width/columns,cellH=canvas.height/rows;videos.forEach((video,index)=>{const x=index%columns*cellW,y=Math.floor(index/columns)*cellH;try{context.drawImage(video,x,y,cellW,cellH);}catch(_){}context.fillStyle='#08101acc';context.fillRect(x+10,y+cellH-38,Math.min(cellW-20,260),27);context.fillStyle='#fff';context.font='18px system-ui';context.fillText(video.closest('.conference-tile')?.querySelector('.conference-tile-name')?.textContent||'参会者',x+20,y+cellH-18);});conference.recordingFrame=requestAnimationFrame(drawConferenceRecording);}
async function startConferenceRecording(){if(!conference||conference.hostID!==conference.selfID)return;if(typeof MediaRecorder==='undefined')throw Error('当前系统组件不支持会议录制');const canvas=document.createElement('canvas');canvas.width=1280;canvas.height=720;const context=canvas.getContext('2d'),videoStream=canvas.captureStream(15),combined=new MediaStream(videoStream.getVideoTracks()),recording={canvas,context,combined,chunks:[],code:conference.code,audioContext:null,destination:null,audioSources:new Map(),recorder:null};try{recording.audioContext=new AudioContext();recording.destination=recording.audioContext.createMediaStreamDestination();for(const track of recording.destination.stream.getAudioTracks())combined.addTrack(track);}catch(_){recording.audioContext?.close();recording.audioContext=null;recording.destination=null;}const preferred=['video/webm;codecs=vp8,opus','video/webm'];const mimeType=preferred.find(type=>MediaRecorder.isTypeSupported(type))||'',recorder=new MediaRecorder(combined,mimeType?{mimeType,videoBitsPerSecond:3500000}:undefined);recording.recorder=recorder;conference.recording=recording;syncConferenceRecordingAudio();recorder.ondataavailable=event=>{if(event.data.size)recording.chunks.push(event.data);};recorder.onstop=()=>{if(recording.chunks.length){const blob=new Blob(recording.chunks,{type:recorder.mimeType||'video/webm'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='YuDesk-会议-'+recording.code+'-'+new Date().toISOString().replace(/[:.]/g,'-')+'.webm';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),30000);}for(const value of recording.audioSources.values())value.source.disconnect();for(const track of combined.getTracks())track.stop();recording.audioContext?.close();};recorder.start(1000);drawConferenceRecording();const state=conference.states.get(conference.selfID);state.recording=true;sendConferenceState();$('conferenceRecord').setAttribute('aria-pressed','true');$('conferenceRecord').querySelector('small').textContent='停止录制';}
function stopConferenceRecording(room=conference,broadcast=true){const recording=room?.recording;if(!recording)return;cancelAnimationFrame(room.recordingFrame);room.recording=null;if(recording.recorder.state!=='inactive')recording.recorder.stop();const state=room.states.get(room.selfID);if(state)state.recording=false;if(broadcast&&conference===room)sendConferenceState();$('conferenceRecord').setAttribute('aria-pressed','false');$('conferenceRecord').querySelector('small').textContent='录制';}
$('conferenceRecord').onclick=async()=>{try{if(conference?.recording)stopConferenceRecording();else await startConferenceRecording();}catch(error){notice('录制无法开始：'+error.message);}};
$('conferenceFullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(error){notice('无法进入全屏：'+error.message);}};document.addEventListener('fullscreenchange',()=>document.body.classList.toggle('conference-fullscreen',!!document.fullscreenElement));
async function leaveConference(confirm=true,endIfHost=true){if(!conference)return;const active=conference,isHost=active.selfID&&active.selfID===active.hostID;if(confirm&&!await window.yudeskConfirm(isHost&&endIfHost?'结束本次会议？所有参会成员将同时离开，会议号立即失效。':'离开本次会议？'))return;if(isHost&&endIfHost)sendConference({type:'end'});active.intentional=true;conference=null;cleanupConference(active);if(isHost&&endIfHost&&active.requestedHost&&local?.meetingCode===active.code)request('/api/local/meeting/end',{}).catch(()=>{});}
function cleanupConference(active){clearInterval(active.heartbeat);stopConferenceMicMeter(active);if(active.recording)stopConferenceRecording(active,false);active.ws?.close();for(const entry of active.peers.values())closeConferencePeer(entry);for(const item of active.audioElements?.values()||[]){item.audio.pause();item.audio.srcObject=null;item.audio.remove();}active.audioElements?.clear();for(const track of active.stream?.getTracks()||[])track.stop();for(const track of active.screen?.getTracks()||[]){track.onended=null;track.stop();}document.body.classList.remove('conference-live','conference-fullscreen');$('conferenceRoom').hidden=true;conferenceAudioPanel.hidden=true;conferenceAudioSettings.setAttribute('aria-pressed','false');$('conferenceGrid').replaceChildren();$('conferenceMemberList').replaceChildren();$('conferenceRecording').hidden=true;if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});}
$('conferenceLeave').onclick=()=>leaveConference(true,true);
for(const [id,path] of [['receiving','receiving'],['filePermission','files']])$(id).onchange=async()=>{const control=$(id);control.disabled=true;try{await request('/api/local/'+path,{enabled:control.checked});updateLocal(await request('/api/local/status'));}catch(error){notice(error.message);control.checked=!control.checked;}finally{control.disabled=false;}};
$('activateForm').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;try{await request('/api/local/activate',{key:$('activationKey').value});$('activationKey').value='';$('activation').open=false;notice('授权已提交，请稍候同步状态');updateLocal(await request('/api/local/status'));}catch(error){notice(error.message);}finally{button.disabled=false;}};
$('hideApp').onclick=async()=>{try{await request('/api/local/hide',{});}catch(error){notice(error.message);}};
function state(status){if(!status)return ['检测中','neutral'];if(!status.online)return ['离线','neutral'];if(status.connected)return ['连接中','good'];if(!status.active)return ['未激活','warning'];if(status.ready===false)return ['准备中','warning'];return ['在线','good'];}
function updateBadges(){for(const el of document.querySelectorAll('[data-presence-id]')){const [text,color]=state(statuses.get(el.dataset.presenceId));el.textContent=text;el.className='badge '+color;}for(const el of document.querySelectorAll('[data-dot-id]'))el.classList.toggle('online',!!statuses.get(el.dataset.dotId)?.online);}
function selectDevice(id){tab('remote');$('targetCode').value=formatted(id);$('targetPIN').value='';$('targetPIN').focus();scheduleCheck();}
function makeIcon(id){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),use=document.createElementNS(svg.namespaceURI,'use');use.setAttribute('href','#'+id);svg.append(use);return svg;}
function renderDevices(force=false){const data=[...(local?[{deviceID:local.code||local.id,name:local.name,local:true}]:[]),...records].map(r=>({...r,displayCode:statuses.get(r.deviceID)?.deviceCode||r.deviceID}));const next=JSON.stringify(data);if(!force&&next===signature){updateBadges();return;}signature=next;const fragment=document.createDocumentFragment();for(const record of data){const row=document.createElement('div');row.className='device-row';row.dataset.search=(record.name+' '+record.deviceID+' '+record.displayCode).toLowerCase();const nameCell=document.createElement('div'),label=document.createElement('div'),name=document.createElement('strong'),hint=document.createElement('small');name.textContent=record.name||'未命名设备';hint.textContent=record.local?'这台电脑':'已保存设备';label.append(name,hint);nameCell.append(makeIcon('monitor'),label);const code=document.createElement('span');code.className='code';code.textContent=record.local&&!local?.code?'正在分配':formatted(record.displayCode||statuses.get(record.deviceID)?.deviceCode||record.deviceID);const statusCell=document.createElement('span');statusCell.dataset.presenceId=record.deviceID;const actions=document.createElement('div');actions.className='device-actions';if(!record.local){const connect=document.createElement('button');connect.type='button';connect.textContent='连接';connect.onclick=()=>selectDevice(record.displayCode||statuses.get(record.deviceID)?.deviceCode||record.deviceID);const remove=document.createElement('button');remove.type='button';remove.textContent='移除';remove.onclick=async()=>{try{await request('/api/local/device/remove',{code:record.deviceID});await loadDevices();}catch(error){notice(error.message);}};actions.append(connect,remove);}else{actions.textContent='本机';actions.classList.add('subtle');}row.append(nameCell,code,statusCell,actions);fragment.append(row);}$('deviceRows').replaceChildren(fragment);$('deviceCount').textContent=String(data.length);const recent=document.createDocumentFragment();for(const record of records.slice(0,3)){const button=document.createElement('button');button.className='recent-card';const label=document.createElement('div'),name=document.createElement('strong'),code=document.createElement('small'),dot=document.createElement('span');name.textContent=record.name||'远程设备';code.textContent=formatted(record.displayCode||statuses.get(record.deviceID)?.deviceCode||record.deviceID);dot.className='dot';dot.dataset.dotId=record.deviceID;label.append(name,code);button.append(makeIcon('monitor'),label,dot);button.onclick=()=>selectDevice(record.displayCode||statuses.get(record.deviceID)?.deviceCode||record.deviceID);recent.append(button);}if(!records.length){const empty=document.createElement('p');empty.className='empty';empty.textContent='连接过的设备会显示在这里，也可在设备列表中手动添加。';recent.append(empty);}$('recentList').replaceChildren(recent);filterDevices();updateBadges();}
function filterDevices(){const needle=normalized($('deviceSearch').value).toLowerCase(),rows=[...document.querySelectorAll('.device-row')],matched=rows.filter(row=>row.dataset.search.replace(/\s/g,'').includes(needle)),size=Math.max(1,Math.min(6,Math.floor((innerHeight-(innerWidth<=500?290:240))/49))),pages=Math.max(1,Math.ceil(matched.length/size));devicePage=Math.min(devicePage,pages-1);const selected=new Set(matched.slice(devicePage*size,(devicePage+1)*size));for(const row of rows)row.hidden=!selected.has(row);$('emptyDevices').hidden=matched.length>0;$('devicePrev').disabled=devicePage===0;$('deviceNext').disabled=devicePage>=pages-1;$('devicePageInfo').textContent=(devicePage+1)+' / '+pages+' · 共 '+matched.length+' 台';}
$('deviceSearch').oninput=()=>{devicePage=0;filterDevices();};
$('devicePrev').onclick=()=>{devicePage=Math.max(0,devicePage-1);filterDevices();};$('deviceNext').onclick=()=>{devicePage++;filterDevices();};window.addEventListener('resize',filterDevices);
async function loadDevices(){try{const result=await request('/api/devices');updateLocal(result.local);records=result.devices||[];renderDevices();await refreshStatuses();}catch(error){notice(error.message);}}
async function queryStatuses(ids){const unique=[...new Set(ids.filter(validCode))];if(!unique.length)return [];const result=await request('/api/device/status',undefined,{ids:unique.join(',')});return result.devices||[];}
async function refreshStatuses(){try{for(const status of await queryStatuses(records.map(r=>r.deviceID)))statuses.set(status.id,status);renderDevices();updateBadges();}catch(_){for(const r of records)statuses.delete(r.deviceID);updateBadges();}}
$('refreshDevices').onclick=loadDevices;loadDevices();setInterval(()=>{loadDevices();if(validCode(normalized($('targetCode').value)))scheduleCheck(0);},30000);
$('addDevice').onclick=()=>{$('addName').value='';$('addCode').value='';$('addDialog').showModal();};$('cancelAdd').onclick=()=>$('addDialog').close();$('addForm').onsubmit=async event=>{event.preventDefault();try{await request('/api/local/device/add',{code:normalized($('addCode').value),name:$('addName').value});$('addDialog').close();await loadDevices();}catch(error){notice(error.message);}};
function targetStatus(text,color=''){$('targetStatus').textContent=text;$('targetStatus').className='presence '+color;}
function scheduleCheck(delay=350){const seq=++checkSequence;clearTimeout(checkTimer);const id=normalized($('targetCode').value);targetStatus(validCode(id)?'检测中…':'输入 9 位设备码检测在线状态');if(!validCode(id))return;checkTimer=setTimeout(async()=>{try{const response=await queryStatuses([id]);if(seq!==checkSequence||id!==normalized($('targetCode').value))return;const found=response.find(s=>s.id===id);statuses.set(id,found);const [text,color]=state(found);targetStatus(text,color==='good'?'online':'offline');}catch(_){if(seq===checkSequence)targetStatus('无法检测，请检查网络','offline');}},delay);}
$('targetCode').oninput=()=>{const value=normalized($('targetCode').value);if(/^\d{0,9}$/.test(value))$('targetCode').value=value.replace(/(\d{3})(?=\d)/g,'$1 ');scheduleCheck();};
$('targetCode').addEventListener('paste',event=>{const text=event.clipboardData?.getData('text')||'',code=text.match(/设备码[：:]\s*([\d ]{9,11})/),pin=text.match(/PIN[：:]\s*(\d{6})/i);if(code&&pin){event.preventDefault();$('targetCode').value=formatted(normalized(code[1]));$('targetPIN').value=pin[1];scheduleCheck();}});
$('connectForm').onsubmit=async event=>{event.preventDefault();if(submitting)return;const id=normalized($('targetCode').value);if(!validCode(id)){notice('请输入 9 位数字设备码');return;}if(local&&(id===local.code||id===local.id)){notice('不能连接本机，请输入另一台设备的设备码');return;}if($('targetPIN').value&&!/^\d{6}$/.test($('targetPIN').value)){notice('请输入对方的 6 位 PIN');return;}submitting=true;$('connectButton').disabled=true;try{const rows=await queryStatuses([id]);if(id!==normalized($('targetCode').value))throw Error('设备码已改变，请重新连接');const s=rows.find(row=>row.id===id);if(!s||!s.online)throw Error('设备离线，请先在对方电脑打开 YuDesk');if(s.connected)throw Error('对方设备已有连接');if(!s.active)throw Error('对方设备尚未激活');if(s.ready===false)throw Error('对方正在准备通道，请稍后重试');$('targetCode').value=id;HTMLFormElement.prototype.submit.call(event.target);}catch(error){notice(error.message);submitting=false;$('connectButton').disabled=false;}};
if($('targetCode').value)scheduleCheck(0);
let serviceBusy=false,setupPrompted=false,serviceSnapshot=null,preferredMode='installed';
try{if(localStorage.getItem('yudesk.runMode')==='portable')preferredMode='portable';}catch(_){}
$('runMode').value=preferredMode;
function rememberMode(mode){preferredMode=mode;$('runMode').value=mode;try{localStorage.setItem('yudesk.runMode',mode);}catch(_){}}
async function serviceStatus(){try{const s=await request('/api/local/service/status');serviceSnapshot=s;$('windowsService').hidden=!s.supported;$('serviceStatus').textContent=s.message;$('installService').textContent=s.updateRequired?'更新并启用当前版本':s.installed?'修复 / 更新安装版':'安装并启用';$('restartInstalled').hidden=!s.installed||s.trustedClient||s.updateRequired||!s.running;$('removeService').hidden=!s.installed;
if(s.packageManaged){$('serviceTitle').textContent='安装与运行';$('serviceDescription').textContent=s.platform==='darwin'?'默认使用 macOS 安装包，安装到“应用程序”。更新时重新运行安装包；屏幕录制与辅助功能仍需本机明确授权。':'默认使用 Linux 安装包，通过软件安装器安装或更新。适用 Debian 12+ / Ubuntu 22.04+；屏幕共享与输入仍受桌面权限限制。';$('installService').hidden=true;$('restartInstalled').hidden=true;$('removeService').hidden=true;$('runMode').value='installed';$('runMode').disabled=true;return;}
if(s.supported&&!s.trustedClient&&!setupPrompted&&!serviceBusy&&preferredMode==='installed'&&document.body.dataset.installPrompt==='true'){setupPrompted=true;await serviceAction(s.installed&&!s.updateRequired&&s.running?'restart':'install',true);}
}catch(_){}finally{setTimeout(serviceStatus,3000);}}
serviceStatus();
async function serviceAction(action,confirmed=false){if(serviceBusy)return;if(action==='remove'&&!confirmed&&!await window.yudeskConfirm('卸载桌面服务后，将无法远程操作 Windows 锁屏界面。继续？'))return;serviceBusy=true;const buttons=['installService','removeService','restartInstalled','runMode'];for(const id of buttons)$(id).disabled=true;$('serviceAction').textContent=action==='restart'?'正在切换到当前安装版…':action==='install'?'正在启动系统管理员授权并安装…':'正在卸载桌面服务…';try{const submit=async value=>{const response=await fetch(endpoint('/api/local/service/'+value),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmed:true}),signal:AbortSignal.timeout(185000)});if(!response.ok)throw Error((await response.text()).slice(0,300));};await submit(action);if(action==='remove'){rememberMode('portable');$('serviceAction').textContent='桌面服务已卸载。';}else{rememberMode('installed');if(action==='install'){const s=await request('/api/local/service/status');if(!s.installed||s.updateRequired||!s.running)throw Error('安装版本尚未就绪，请检查后重试');if(!s.trustedClient){$('serviceAction').textContent='安装成功，正在切换到当前安装版…';await submit('restart');}else $('serviceAction').textContent='安装版已更新并启用。';}else $('serviceAction').textContent='正在打开当前安装版，请稍候。';}}catch(e){$('serviceAction').textContent='操作未完成：'+e.message;}finally{serviceBusy=false;for(const id of buttons)$(id).disabled=false;}}
$('runMode').onchange=async()=>{rememberMode($('runMode').value);if(preferredMode==='installed'&&serviceSnapshot&&!serviceSnapshot.trustedClient)await serviceAction(serviceSnapshot.installed&&!serviceSnapshot.updateRequired&&serviceSnapshot.running?'restart':'install');};
$('installService').onclick=()=>serviceAction('install');$('removeService').onclick=()=>serviceAction('remove');$('restartInstalled').onclick=()=>serviceAction('restart');
